.PHONY: install uninstall deps

deps:
	echo "Installing dependencies for magic-link-auth..."
	lamdera install elm/bytes
	lamdera install elm/http
	lamdera install elm/random
	lamdera install chelovek0v/bbase64
	lamdera install TSFoster/elm-sha1
	lamdera install pzp1997/assoc-list
	lamdera install elm/parser
	lamdera install dillonkearns/elm-markdown
	lamdera install ianmackenzie/elm-units
	lamdera install TSFoster/elm-uuid
	lamdera install mgold/elm-nonempty-list
	lamdera install rtfeldman/elm-hex
	lamdera install billstclair/elm-sha256
	lamdera install elm/time
	lamdera install elmcraft/core-extra
	lamdera install MartinSStewart/elm-nonempty-string
